---
- name: Create cert-manager namespace
  k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

- name: Add jetstack chart repo
  helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert-manager
  helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    state: present
    values:
      installCRDs: true
      extraArgs:
        # Tailscale may replace /etc/resolv.conf with the private nameserver
        # deployed by the dns role. The private nameserver's SOA record may not
        # be the same as public DNS, so force public DNS.
        - --dns01-recursive-nameservers-only
        - --dns01-recursive-nameservers=8.8.8.8:53

- name: Create ClusterIssuer
  k8s:
    definition: "{{ lookup('template', 'templates/manifest.yml') }}"
    state: present
