---
- name: Create cert-manager namespace
  k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present

- name: Add jetstack chart repo
  helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert-manager
  helm:
    force: true
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    state: present
    values:
      installCRDs: true

- name: Create ClusterIssuer
  k8s:
    definition: "{{ lookup('template', 'templates/manifest.yml') }}"
    state: present
