---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: bootstrap
      tags: ['bootstrap']

    - role: prereq
      tags: ['k3s']

    - role: download
      tags: ['k3s']

    - role: raspberrypi
      tags: ['k3s']

- hosts: master
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"
  roles:
    - role: k3s/master
      tags: ['k3s']

    - role: setup
      tags: ['apps', 'setup']

    - role: monitoring
      tags: ['apps', 'monitoring']

    - role: dokuwiki
      tags: ['apps', 'dokuwiki']

- hosts: node
  become: yes
  roles:
    - role: k3s/node
      tags: ['k3s']
