---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: bootstrap
      tags: ['bootstrap']

    - role: artis3n.tailscale
      tags: ['tailscale']

    - role: prereq
      tags: ['k3s']

    - role: download
      tags: ['k3s']

    - role: raspberrypi
      tags: ['k3s']

  tasks:
    - name: Echo tailscale IP
      tags: ['never', 'debug']
      debug:
        msg: "{{ tailscale_ip }}"

    - name: Echo tailscale ingress server IP
      tags: ['never', 'debug']
      debug:
        msg: "{{ tailscale_ingress_server_ip }}"

- hosts: master
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"
  roles:
    - role: k3s/master
      tags: ['k3s']

    - role: setup
      tags: ['apps', 'setup']

    - role: dns
      tags: ['dns', 'setup']

    - role: tls
      tags: ['tls', 'setup']

    - role: longhorn
      tags: ['longhorn', 'setup']

    - role: monitoring
      tags: ['apps', 'monitoring']

    - role: dokuwiki
      tags: ['apps', 'dokuwiki']

    - role: gitea
      tags: ['apps', 'gitea']

    - role: openethereum
      tags: ['apps', 'openethereum']

    - role: nextcloud
      tags: ['apps', 'nextcloud']

- hosts: node
  become: yes
  environment:
    PATH: "~/go/bin:{{ ansible_env.PATH }}"
  roles:
    - role: k3s/node
      tags: ['k3s']
