---
- name: Create longhorn namespace
  k8s:
    name: longhorn-system
    api_version: v1
    kind: Namespace
    state: present

- name: Add longhorn chart repo
  helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install open-iscsi
  tags: ['longhorn:open-iscsi']
  become: yes
  package:
    name:
      - open-iscsi
    state: present
  delegate_to: "{{ item }}"
  loop: "{{ groups['k3s_cluster'] }}"

- name: Deploy longhorn
  helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    state: present

- name: Create storage class for single replica
  tags: ['longhorn:r1']
  k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-r1
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      parameters:
        baseImage: ""
        fromBackup: ""
        numberOfReplicas: "1"
        staleReplicaTimeout: "30"

- name: Mark "longhorn" storage class as non-default
  k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-r1
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    state: present

- name: Mark "local-path" storage class as non-default
  k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    state: present

- name: Create longhorn-ui ingress
  k8s:
    definition:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: longhorn-ingress
        namespace: longhorn-system
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          cert-manager.io/acme-challenge-type: dns01
      spec:
        rules:
          - host: longhorn.homelab.markhudnall.com
            http:
              paths:
                - path: /
                  backend:
                    serviceName: longhorn-frontend
                    servicePort: 80
        tls:
          - hosts:
              - longhorn.homelab.markhudnall.com
            secretName: longhorn-homelab-markhudnall-com-tls
