---

  - name: Restart dhcpcd
    become: yes
    service:
      name: dhcpcd
      state: restarted

  - name: Restart Networking
    become: yes
    service:
      name: networking
      state: restarted
