kind: Deployment
apiVersion: apps/v1
metadata:
  name: eth2-prometheus-exporter
  namespace: eth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth2-prometheus-exporter
  template:
    metadata:
      labels:
        app: eth2-prometheus-exporter
    spec:
      containers:
        - name: eth2-prometheus-exporter
          image: landakram/eth2-prometheus-exporter:v0.0.2
          args:
          - "--beacon-chain-address=lighthouse:5052"
          - "--validator-indices={{ eth2_prometheus_exporter_validator_indices }}"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '256Mi'

---
kind: Service
apiVersion: v1
metadata:
  name: eth2-prometheus-exporter
  namespace: eth2
  labels:
    app: eth2-prometheus-exporter
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: eth2-prometheus-exporter

---
kind: ServiceMonitor
apiVersion: v1
metadata:
  name: eth2-prometheus-exporter
  namespace: eth2
  labels:
    app: eth2-prometheus-exporter
spec:
  endpoints:
    - port: exporter
      scheme: http
      interval: 5s
  selector:
    matchLabels:
      app: eth2-prometheus-exporter
